cmake_minimum_required(VERSION 3.16)

project(Zeta_Avionics VERSION 0.1 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(Qt6 REQUIRED COMPONENTS Quick)

qt_standard_project_setup(REQUIRES 6.10)

# Content of downloaded design from Figma to Qt or similar
if (EXISTS "${CMAKE_CURRENT_LIST_DIR}/importedcontent/CMakeLists.txt")
    add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/importedcontent)
endif()

qt_add_executable(appZeta_Avionics
    src/main.cpp
)

set_source_files_properties(qml/Theme.qml
    PROPERTIES
        QT_QML_SINGLETON_TYPE TRUE
)

qt_add_qml_module(appZeta_Avionics
    URI Zeta_Avionics
    QML_FILES
        qml/Main.qml
        qml/Theme.qml
        qml/scenes/StartupScene.qml
        qml/scenes/OverviewScene.qml
        qml/components/SpacecraftModel/Futuristic_spacecraft_3dmodel.qml
        qml/components/SpacecraftView.qml
    RESOURCES
        assets/fonts/IBMPlexMono-Regular.ttf
        assets/fonts/IBMPlexMono-Medium.ttf
        assets/fonts/IBMPlexMono-SemiBold.ttf
        assets/fonts/IBMPlexMono-Bold.ttf
        assets/background/Photoman61.mp4
        qml/components/SpacecraftModel/meshes/meshes_0__mesh.mesh
        qml/components/SpacecraftModel/maps/textureData.jpg
        qml/components/SpacecraftModel/maps/textureData8.png
        qml/components/SpacecraftModel/maps/textureData10.jpg
)

# Qt for iOS sets MACOSX_BUNDLE_GUI_IDENTIFIER automatically since Qt 6.1.
# If you are developing for iOS or macOS you should consider setting an
# explicit, fixed bundle identifier manually though.
set_target_properties(appZeta_Avionics PROPERTIES
#    MACOSX_BUNDLE_GUI_IDENTIFIER com.example.appZeta_Avionics
    MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION}
    MACOSX_BUNDLE_SHORT_VERSION_STRING ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
    MACOSX_BUNDLE TRUE
    WIN32_EXECUTABLE TRUE
)

target_link_libraries(appZeta_Avionics
    PRIVATE Qt6::Quick
)

install(TARGETS appZeta_Avionics
    BUNDLE DESTINATION .
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)
